In [3]:
import pandas as pd

In [4]:
dados = pd.read_csv('data_base/fifa.csv')

In [6]:
dados.loc[dados['Nationality'] == 'Brazil'] # Retorna todos os jogadores que tem 'Nationality' == 'Brazil'

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
27,27,200145,Casemiro,26,https://cdn.sofifa.org/players/4/19/200145.png,Brazil,https://cdn.sofifa.org/flags/54.png,88,90,Real Madrid,...,84.0,88.0,90.0,87.0,13.0,14.0,16.0,12.0,12.0,€126.4M
32,32,189242,Coutinho,26,https://cdn.sofifa.org/players/4/19/189242.png,Brazil,https://cdn.sofifa.org/flags/54.png,88,89,FC Barcelona,...,85.0,55.0,54.0,47.0,12.0,7.0,9.0,14.0,6.0,€147.7M
35,35,176676,Marcelo,30,https://cdn.sofifa.org/players/4/19/176676.png,Brazil,https://cdn.sofifa.org/flags/54.png,88,88,Real Madrid,...,86.0,71.0,85.0,86.0,12.0,5.0,5.0,5.0,9.0,€88.2M
39,39,164240,Thiago Silva,33,https://cdn.sofifa.org/players/4/19/164240.png,Brazil,https://cdn.sofifa.org/flags/54.png,88,88,Paris Saint-Germain,...,81.0,88.0,89.0,85.0,9.0,12.0,5.0,9.0,10.0,€44.4M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17059,17059,243750,Gianluca Zanette,21,https://cdn.sofifa.org/players/4/19/243750.png,Brazil,https://cdn.sofifa.org/flags/54.png,55,66,Vejle Boldklub,...,35.0,21.0,12.0,11.0,55.0,57.0,55.0,54.0,56.0,€174K
17446,17446,235949,Strefezza,21,https://cdn.sofifa.org/players/4/19/235949.png,Brazil,https://cdn.sofifa.org/flags/54.png,54,62,US Cremonese,...,43.0,33.0,15.0,15.0,15.0,15.0,8.0,10.0,6.0,NaN
17588,17588,244311,Lucas Ribeiro,19,https://cdn.sofifa.org/players/4/19/244311.png,Brazil,https://cdn.sofifa.org/flags/54.png,53,71,Valenciennes FC,...,44.0,24.0,27.0,22.0,13.0,14.0,14.0,11.0,13.0,€309K
17611,17611,241268,Felipe Ferreyra,20,https://cdn.sofifa.org/players/4/19/241268.png,Brazil,https://cdn.sofifa.org/flags/54.png,53,67,Curicó Unido,...,47.0,33.0,15.0,16.0,13.0,6.0,5.0,5.0,6.0,€257K
18170,18170,246447,Nicolas Firmino,17,https://cdn.sofifa.org/players/4/19/246447.png,Brazil,https://cdn.sofifa.org/flags/54.png,48,70,New England Revolution,...,41.0,29.0,32.0,40.0,12.0,8.0,11.0,9.0,12.0,€147K

In [ ]:
dados.loc[dados['Age'] == 25] # Retorna todos os jogadores que a idade é = 25

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
9,9,200389,J. Oblak,25,https://cdn.sofifa.org/players/4/19/200389.png,Slovenia,https://cdn.sofifa.org/flags/44.png,90,93,Atlético Madrid,...,70.0,27.0,12.0,18.0,86.0,92.0,78.0,88.0,89.0,€144.5M
43,43,201399,M. Icardi,25,https://cdn.sofifa.org/players/4/19/201399.png,Argentina,https://cdn.sofifa.org/flags/52.png,87,90,Inter,...,85.0,45.0,24.0,20.0,13.0,9.0,5.0,7.0,9.0,€114.5M
45,45,195864,P. Pogba,25,https://cdn.sofifa.org/players/4/19/195864.png,France,https://cdn.sofifa.org/flags/18.png,87,91,Manchester United,...,87.0,66.0,70.0,68.0,5.0,6.0,2.0,4.0,3.0,€123.2M
47,47,192505,R. Lukaku,25,https://cdn.sofifa.org/players/4/19/192505.png,Belgium,https://cdn.sofifa.org/flags/7.png,87,89,Manchester United,...,83.0,30.0,30.0,30.0,8.0,15.0,14.0,7.0,10.0,€120.3M
62,62,201535,R. Varane,25,https://cdn.sofifa.org/players/4/19/201535.png,France,https://cdn.sofifa.org/flags/18.png,86,91,Real Madrid,...,82.0,87.0,88.0,87.0,11.0,11.0,9.0,5.0,14.0,€106.3M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17637,17637,241294,Li Fang,25,https://cdn.sofifa.org/players/4/19/241294.png,China PR,https://cdn.sofifa.org/flags/155.png,53,56,Chongqing Dangdai Lifan FC SWM Team,...,36.0,64.0,61.0,55.0,14.0,6.0,11.0,6.0,5.0,€134K
17638,17638,236431,E. Alarcón,25,https://cdn.sofifa.org/players/4/19/236431.png,Argentina,https://cdn.sofifa.org/flags/52.png,53,57,Patronato,...,47.0,12.0,10.0,14.0,56.0,55.0,55.0,50.0,52.0,€76K
17661,17661,224681,Wen Zhixiang,25,https://cdn.sofifa.org/players/4/19/224681.png,China PR,https://cdn.sofifa.org/flags/155.png,53,56,Henan Jianye FC,...,29.0,11.0,13.0,19.0,52.0,45.0,44.0,53.0,60.0,€111K
17750,17750,210714,J. Skov Hansen,25,https://cdn.sofifa.org/players/4/19/210714.png,Denmark,https://cdn.sofifa.org/flags/13.png,52,55,Randers FC,...,44.0,35.0,37.0,36.0,13.0,15.0,6.0,11.0,15.0,€80K
17928,17928,232789,T. Nakagawa,25,https://cdn.sofifa.org/players/4/19/232789.png,Japan,https://cdn.sofifa.org/flags/163.png,51,52,Yokohama F. Marinos,...,52.0,34.0,10.0,11.0,10.0,11.0,11.0,13.0,9.0,€93K

In [ ]:
dados.sort_values('Name') # Retorna os nome em ordem alfabética

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
13632,13632,228006,A. Abang,21,https://cdn.sofifa.org/players/4/19/228006.png,Cameroon,https://cdn.sofifa.org/flags/103.png,62,69,New York Red Bulls,...,45.0,32.0,17.0,21.0,6.0,6.0,7.0,13.0,9.0,€723K
15665,15665,243896,A. Abdellaoui,25,https://cdn.sofifa.org/players/4/19/243896.png,Algeria,https://cdn.sofifa.org/flags/97.png,59,64,FC Sion,...,51.0,61.0,66.0,65.0,15.0,10.0,14.0,13.0,14.0,€259K
3055,3055,198076,A. Abdennour,28,https://cdn.sofifa.org/players/4/19/198076.png,Tunisia,https://cdn.sofifa.org/flags/145.png,73,73,Olympique de Marseille,...,75.0,68.0,73.0,75.0,12.0,8.0,7.0,8.0,15.0,NaN
6388,6388,138698,A. Abdi,31,https://cdn.sofifa.org/players/4/19/138698.png,Switzerland,https://cdn.sofifa.org/flags/47.png,69,69,Sheffield Wednesday,...,75.0,47.0,60.0,57.0,9.0,6.0,8.0,11.0,8.0,€1.7M
12816,12816,245438,A. Abdu Jaber,21,https://cdn.sofifa.org/players/4/19/245438.png,Eritrea,https://cdn.sofifa.org/flags/113.png,63,65,Al Wehda,...,49.0,17.0,13.0,15.0,7.0,11.0,7.0,6.0,12.0,€843K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15334,15334,246284,Óscar Gil,20,https://cdn.sofifa.org/players/4/19/246284.png,Spain,https://cdn.sofifa.org/flags/45.png,59,69,Elche CF,...,45.0,53.0,65.0,66.0,14.0,14.0,11.0,8.0,11.0,€385K
9803,9803,229865,Óscar Pinchi,22,https://cdn.sofifa.org/players/4/19/229865.png,Spain,https://cdn.sofifa.org/flags/45.png,66,77,Atlético Madrid,...,63.0,50.0,39.0,34.0,5.0,12.0,6.0,12.0,13.0,€2.5M
2564,2564,208621,Óscar Plano,27,https://cdn.sofifa.org/players/4/19/208621.png,Spain,https://cdn.sofifa.org/flags/45.png,74,74,Real Valladolid CF,...,69.0,31.0,30.0,26.0,8.0,14.0,16.0,8.0,13.0,€13.2M
10353,10353,243558,Óscar Valentín,23,https://cdn.sofifa.org/players/4/19/243558.png,Spain,https://cdn.sofifa.org/flags/45.png,65,71,CF Rayo Majadahonda,...,60.0,66.0,63.0,65.0,11.0,8.0,13.0,10.0,8.0,€1.3M
10002,10002,220433,Óscar Whalley,24,https://cdn.sofifa.org/players/4/19/220433.png,Spain,https://cdn.sofifa.org/flags/45.png,65,70,Aarhus GF,...,51.0,23.0,18.0,16.0,66.0,65.0,68.0,63.0,66.0,€696K

In [ ]:
dados.sort_values('Name', ascending=False) # Retorna os nome em ordem alfabética - INVERTIDA